# Generated by Django 3.0.2 on 2020-01-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_squashed_0002_remove_party_attorneys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
