# Generated by Django 3.0.2 on 2020-01-19 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200119_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Address'),
        ),
    ]
